node {
  def commit_id

  stage('Preparation') {
    checkout scm
    sh "git rev-parse --short HEAD > .git/commit-id"
    commit_id = readFile('.git/commit-id').trim()
  }

  stage('test') {
    nodejs('nodejs17') {
      sh 'npm install --only=Dev'
      sh 'npm test'
    }
  }

  stage('docker build and publish') {
    docker.withRegistry('https://index.docker.io/v1/', 'DockerLoginCreds') {
      def app = docker.build('amit0511/docker-nodejs-demo:${commit_id}', '.').push()
    }
  }
}